"""
Конфигурация сообщений для рассылки
"""

# B2B сообщения (для оптовых клиентов)
MESSAGES_B2B = [
    'Лазерная гравировка клавиатуры | Русификация ноутбука\n⚡ Русификация клавиатур ноутбуков, ПК и механических клавиатур за 10–20 минут.\nРаботаем с любыми моделями — от MacBook, Lenovo, HP, ASUS, Acer, MSI до игровых клавиатур с подсветкой и без.\nУслуги:\n✅ Лазерная гравировка клавиатуры (символы как заводские, не стираются);\n✅ Русификация клавиатуры ноутбука и ПК;\n✅ Гравировка клавиатур с подсветкой и без;\n✅ Работа с любыми производителями (Apple, Lenovo, HP, ASUS, Acer, MSI, Logitech, Razer и др.).\nПреимущества:\n⚡ Быстро — русификация за 10–20 минут;\n💎 Качественно — профессиональное лазерное оборудование;\n📜 Гарантия на выполненные работы;\n🚚 Доставка и выезд при заказе от 10 устройств.\nЦены:\n💻 Ноутбук — от 100 ₽;\n⌨ Механическая клавиатура — от 400 ₽;\n🔥 Оптовые заказы — скидки до 70%.\n📍 Москва.\n💳 Оплата наличными или по счёту (ЭДО).',
    
    '"💨 Техника Dyson в наличии! ⚡\n\n✨ Airwrap \nDyson HS05 Long Prussian Blue Cooper Diffuse - 42800 🇪🇺\nDyson HS05 Long Nickel / Copper - 39800 🇨🇳\nDyson HS05 Long Prussian Blue / Cooper - 40800 🇨🇳\nDyson HS05 Long Blush Blue - 48300 🇮🇱\nDyson HS05 Long Ceramic Pop - 48800 🇭🇰\nDyson HS05 Long Orange Topaz - 57300 🇨🇳\nDyson HS05 Long Diffuse Strawberry Bronze - 40300 🇪🇺\nDyson HS05 Long Diffuse Strawberry Bronze - 47300 🇬🇧\nDyson HS05 Airwrap Complete Short Multi Hair  Vinca Rose Gift Edition - 49300 🇨🇳\nDyson HS05 Long Ceramic Pink - 48300 🇭🇰\nDyson HS01 Airwrap Complete  Multi Hair  Fuchsia Nickel с чехлом - 53300 🇨🇳\nDyson HS01 Airwrap Complete  Multi Hair  Prussian Blue с чехлом,расческой и гребнем - 55300 🇨🇳\n\nDyson HS07 Corrale Cooper/Nickel - 32300 🇮🇳\n\nDyson HS08 Jusper Plum Strait+Wavy - 37300 🇨🇳 🇭🇰\nDyson HS08 Jusper Plum Strait+Wavy - 42300 🇰🇷 🇪🇺\n\nDyson HS09 Airwrap Co-Anda 2X  Ceramic Pink - 64800 🇰🇷\nDyson HS09 Airwrap Co-Anda 2X Jasper Plum - 70300 🇰🇷\n\n✨ Фены Dyson Supersonic\nDyson HD07 Antrazit/Fuchsia - 37300 \nDyson HD07 Prussian Blue Cooper - без кейса - 32300 🇪🇺\nDyson HD07 Blush Blue - без кейса - 33300 🇦🇺\n\nDyson HD08 Topaz Orange - без кейса - 40300 🇰🇷\nDyson HD08 Nickel/Cooper - без кейса - 34300 🇮🇳\nDyson HD08 Blue/Cooper - без кейса - 35300 🇮🇳\nDyson HD08 Blue/Gold - без кейса - 34800 🇰🇷\n\nDyson HD15 Ceramic Pink - без кейса - 33300 🇭🇰\nDyson HD15 Prussian Blue Cooper - без кейса - 33300 🇭🇰\n\nDyson HD16 Strawberry Bronze -без кейса - 29800 🇭🇰\nDyson HD16 Red Velvet/Gold -без кейса - 35800 🇭🇰\nDyson HD16 Jasper Plum -без кейса - 27500 🇭🇰\nSuperSonic Nural HD16 Kanzan Pink - с кейсом - 31300 🇭🇰\nDyson HD16 Strawberry Bronze -без кейса - 30700 🇪🇺\n\nDyson HD17 Supersonic R Jasper Plum - без кейса - 35300 🇭🇰\n\nDyson HD18 Supersonic R Pro Vinca Blue /Topaz Orange - 34800 🇪🇺\n✨ Пылесосы Dyson V15 Detect\n\nV10 Total Clean Vacuum Nickel/Black - 35800 🇬🇧\n\nV12 Detect Slim Fluffy (синий) - 47800 🇸🇬\n\nV12 Slim Absolute detected Yellow/Nickel - 37300 🇬🇧\n\nV12s Slim Submarine Complete Gold/Gold - 51300 🇸🇬\nV12s Slim Submarine Yellow/Nickel - 46800 🇸🇬\n\nV15 SV47 Detect Absolute Yellow/Nickel - 48300 🇪🇺\nV15 SV47 Detect Absolute Yellow/Nickel - 47800 🇬🇧\nV15 SV47 Detect Absolute Gold/Gold - 49800 🇪🇺\nV15 SV47 Detect Absolute Total Clean - 56300 🇬🇧\n\nV15s Detect Submarine Yellow/Nickel SV47 - 64300 🇪🇺\nV15s Detect Submarine Yellow/Nickel SV47 - 57300 🇬🇧\n\n⚡ Всё новое, в наличии\n🚚 Удобная доставка\n✅ Оригинал"',
    
    # Добавьте остальные B2B сообщения из config_mesВ2B.py
]

# B2C сообщения (для розничных клиентов)  
MESSAGES_B2C = [
    'Давно искали надежный магазин электроники ? \u2028\u2028Тогда магазин Яблочный Гусь для вас !\u2028\u2028Почему стоит выбрать магазин «Яблочный Гусь»:\n✅ Только оригинальная продукция Apple /  Samsung / Sony / Dyson \n✅ Гарантия 1 год\n✅He активиpовaнный\n✅Чек пpи пoкупке\n✅Hе восстановленный\n✅ Запечaтанный\n✅ Не обмeнный\n✅ Любыe пpoвepки\n📍 г. Москва, м. Багратионовская, Багратионовский проезд 7 корпус 1, Павильон А1-010В, 1 этаж. 2 минуты от метро / парковка рядом с ТЦ\n📦 Доставка по\xa0Москве\xa0за 4 часа.\n📦 Доставка\xa0по России\xa0транспортной компанией СДЭК по полной безопасной предоплате (СБП на счет юридического лица) с комиссией 3%\n🆕\xa0Тrаdе-In\xa0на привлекательных условиях. Обменяй смартфон выгодно!\n⚡ У нас в профиле большой выбор техники Apple и Samsung — от iPhone и MacBook до Watch и AirPods. Зайдите — вы точно найдёте то, что нужно!',
    
    # Добавьте остальные B2C сообщения из config_mesВ2C.py
]
